import type { MenuItem } from "@shared/schema";

//todo: remove mock functionality
export const mockMenuItems: MenuItem[] = [
  {
    id: "1",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice layered with tender chicken, saffron, and traditional spices",
    price: "12.99",
    category: "Biriyani",
    image: "chicken-biryani",
    isVegetarian: false,
    spiceLevel: 3,
    rating: "4.8",
    isAvailable: true,
    dietaryInfo: ["Gluten-Free"],
  },
  {
    id: "2",
    name: "Mutton Biryani",
    description: "Premium mutton cooked with fragrant rice, whole spices, and garnished with fried onions",
    price: "15.99",
    category: "Biriyani",
    image: "mutton-biryani",
    isVegetarian: false,
    spiceLevel: 4,
    rating: "4.9",
    isAvailable: true,
    dietaryInfo: ["Gluten-Free"],
  },
  {
    id: "3",
    name: "Vegetable Biryani",
    description: "Fresh mixed vegetables and paneer with aromatic basmati rice and herbs",
    price: "10.99",
    category: "Biriyani",
    image: "veg-biryani",
    isVegetarian: true,
    spiceLevel: 2,
    rating: "4.6",
    isAvailable: true,
    dietaryInfo: ["Vegetarian", "Gluten-Free"],
  },
  {
    id: "4",
    name: "Chicken Samosa (3 pcs)",
    description: "Crispy golden pastry filled with spiced chicken and herbs",
    price: "5.99",
    category: "Starters",
    image: "samosa",
    isVegetarian: false,
    spiceLevel: 2,
    rating: "4.7",
    isAvailable: true,
    dietaryInfo: null,
  },
  {
    id: "5",
    name: "Tandoori Chicken",
    description: "Marinated chicken roasted in tandoor with authentic spices",
    price: "13.99",
    category: "Starters",
    image: "tandoori",
    isVegetarian: false,
    spiceLevel: 3,
    rating: "4.8",
    isAvailable: true,
    dietaryInfo: ["Gluten-Free", "Dairy-Free"],
  },
  {
    id: "6",
    name: "Butter Chicken",
    description: "Tender chicken in creamy tomato-based curry with butter and cream",
    price: "14.99",
    category: "Main Course",
    image: "butter-chicken",
    isVegetarian: false,
    spiceLevel: 2,
    rating: "4.9",
    isAvailable: true,
    dietaryInfo: ["Gluten-Free"],
  },
  {
    id: "7",
    name: "Mango Lassi",
    description: "Refreshing yogurt drink blended with ripe mangoes",
    price: "4.99",
    category: "Beverages",
    image: "lassi",
    isVegetarian: true,
    spiceLevel: 0,
    rating: "4.7",
    isAvailable: true,
    dietaryInfo: ["Vegetarian", "Gluten-Free"],
  },
  {
    id: "8",
    name: "Gulab Jamun (4 pcs)",
    description: "Soft milk dumplings soaked in rose-flavored sugar syrup",
    price: "6.99",
    category: "Desserts",
    image: "gulab-jamun",
    isVegetarian: true,
    spiceLevel: 0,
    rating: "4.8",
    isAvailable: true,
    dietaryInfo: ["Vegetarian"],
  },
];
